### PR TITLE
Add wireless controller battery status

### PR DESCRIPTION
**Pull request by medusalix**
The current battery type and level of the connected controller is included in a *status* packet that's sent periodically. Because the returned battery level is either high, medium, low or empty, I mapped those values to corresponding percentages. The battery type is currently unused (maybe that could be reflected in the UI at some point).

### CODE REVIEW

**Comment by FranticRain** [comment]
I swear I'll go through both of these soon. I'm installing my Mojave partition as I type this. Do you have any preference on the merge order of these two changes?

**Comment by medusalix** [comment]
@FranticRain No worries, you can test these whenever you like. The battery indicator should probably work on Catalina too, as it doesn't depend on the force feedback plugin. I really don't care about the order the two PRs are merged.

**Comment by FranticRain** [comment]
Code changes look good to me, but I just built out a signed/notarized version and there is no battery indicator visible in the preference pane. For whatever reason, it's not showing up. Does it show up on your system?

**Comment by medusalix** [comment]
@FranticRain Yes it does, you might have to wait for a few seconds for the controller to send the battery status packet.

**Comment by FranticRain** [comment]
Looks like I accidentally installed the wrong version. That's what I get for testing a million different things at once. Looks great.

**Pull request merged**
