### PR TITLE
Add ardwiino to info.plist

### PR DESCRIPTION
**Pull request by sanjay900**
Ardwiino guitar hero controller adaptor added!
https://github.com/sanjay900/Ardwiino

### CODE REVIEW

**Comment by FranticRain** [comment]
Where does the vendor and product ID combination come for this device? If it's a generic combination for the Sparkfun board that you used, then I don't think it should be used for this driver. If you have purchased a VID/PID combo that is unique to this device, then we can use that.

**Comment by sanjay900** [comment]
Yeah I got a unique code from pid.codes

**Comment by FranticRain** [comment]
Let me know if it works: [360ControllerInstall.dmg.zip](https://github.com/360Controller/360Controller/files/3100704/360ControllerInstall.dmg.zip)

**Comment by sanjay900** [comment]
It works

**Pull request merged**
