### PR TITLE
Add wireless controller rumble

### PR DESCRIPTION
**Pull request by medusalix**
Initial rumble implementation for wireless Xbox One controllers.

### CODE REVIEW

**Comment by FranticRain** [comment]
I assume that you've tested this on Mojave and it works? The force feedback plugin doesn't work in Catalina due to full deprecation of `/System/Library/Extensions`. I'd have to install a Mojave partition to test this, unfortunately.

**Comment by FranticRain** [comment]
@medusalix I'll get a signed build of your branch built out for you when I get a chance, and I'll install a Mojave partition to test it out myself, just so we can be sure that we're in a good state.

**Comment by FranticRain** [comment]
Install a Mojave partition and found that both wired and wireless rumble didn't work. Looks like there was a change you made that changed some logic from "if none of these" to "if not one of these," which broke it. You'll need to fix that in this PR. Specifically in `Feedback360/Feedback360.cpp` lines 116-170 and 510-513 look like this:
```C
if (!IOObjectConformsTo(hidDevice, "Xbox360ControllerClass") ||
    !IOObjectConformsTo(hidDevice, "Wireless360Controller") ||
    !IOObjectConformsTo(hidDevice, "WirelessOneController")
) {
```
but it should be this:
```C
if (!IOObjectConformsTo(hidDevice, "Xbox360ControllerClass") &&
    !IOObjectConformsTo(hidDevice, "Wireless360Controller") &&
    !IOObjectConformsTo(hidDevice, "WirelessOneController")
) {
```
Once I got that patched up and built out, force feedback returned to wired controllers but didn't work for wireless. I don't have time to look into it any further right now.

**Comment by medusalix** [comment]
@FranticRain Oops, sorry about that. Could you send me a signed build of the force feedback plugin that works on Mojave?

**Comment by FranticRain** [comment]
Don't forget to also fix that logic on like 510-ish. I did it for this build.

[360ControllerInstall.dmg.zip](https://github.com/360Controller/360Controller/files/3775464/360ControllerInstall.dmg.zip)

**Comment by medusalix** [comment]
@FranticRain After hours of looking around, I noticed that the `IOHIDDevice` I create from my main service didn't have the `IOCFPlugInTypes` property attached. That's why the force feedback plugin wasn't loading. Everything should be working now (including power off).

**Comment by FranticRain** [comment]
I can confirm that this we have rumble and that power off works as expected. Excellent work as always.

**Pull request merged**
