### PR TITLE
update Simplified Chinese localization

### LINKED ISSUE #848: Chinese localization not working
### OS Version
macOS 10.14.3

### Driver Version
Version 0.16.11

### Detailed Explaination of Issue
I have install the latest version of the driver and it should contain Chinese localization, but is doesn't.
It is still English .

### PR DESCRIPTION
**Pull request by L1cardo**
This may fix #848,  just maybe, but I don't know.

### CODE REVIEW

**Comment by FranticRain** [comment]
Here's a compiled version of your fork. Let me know if it works. [Install360Controller.pkg.zip](https://github.com/360Controller/360Controller/files/2938791/Install360Controller.pkg.zip)

**Comment by L1cardo** [comment]
It still doesn't work.  sad :(

**Comment by L1cardo** [comment]
I have tried uninstall the old version , restart my Mac , install the new version , restart my Mac again.
It is still not working  :(

**Comment by L1cardo** [comment]
sorry to bother，but do you have any idea about this？

**Comment by FranticRain** [comment]
As to why the localization doesn't work? I don't know. I've never localized any applications on macOS before, so I am completely unable to help you with this issue.

**Comment by L1cardo** [comment]
I have localized some apps before,and they worked perfect.
They were apps this a window,not like this which only appeares in setting.Maybe this is the reason?
I don’t know why this doesn’t work either. I don’t know much about coding, I can’t fix by myself , but I will work on it.

**Comment by L1cardo** [comment]
Thanks again for such a marvelous app!

**Pull request merged**
