### PR TITLE
add Simplified Chinese localization

### PR DESCRIPTION
**Pull request by L1cardo**
I have fixed the issue， please have a look

### CODE REVIEW

**Comment by FranticRain** [comment]
Thank you very much for your contribution!

**Comment by L1cardo** [comment]
I failed in buildings pkg file, can you build a pkg file for the new version that contains Chinese localization?  Thanks.

**Comment by FranticRain** [comment]
It should be included in the 0.16.11 release now.

**Comment by L1cardo** [comment]
got it. there was noonly source code in the release page yesterday，but now there is dmg file.
thanks！

**Pull request merged**
