### PR TITLE
Change product string for an Xbox One pad pretending to be a 360 pad

### PR DESCRIPTION
**Pull request by kylewlacy**
At least one game I play had an issue with my new Xbox One pad, with the "pretend to be an Xbox 360 controller" option in the Preference Pane enabled (namely, [Brawlhalla](http://store.steampowered.com/app/291550/), which works with my 360 pad, and actually works with the Xbox One pad as well when this option is *disabled*). Currently, the `XboxOnePretend360Class::newProductString()` method returns "Xbox One Wired Controller (Xbox 360)" as the product string. Changing the string to "Xbox 360 Wired Controller" fixed this particular issue for me.

One minor thing to note with this change is that, in the Preference Pane, the Xbox One controller will be listed as "Xbox 360 Wired Controller (Wired)" on the dropdown when "pretend to be an Xbox 360 controller" is enabled:

"pretend to be an Xbox 360 controller" option enabled

...but there are no other user-facing differences beyond that, AFAICT.

### CODE REVIEW

**Comment by FranticRain** [comment]
Here is an already existing issue that caused the change in that string: #175 

I'd really need input from @pbhogan before I can comment on this either way. Although, I would say that checking for a matching name is a pretty dumb way to implement your controller support.

**Comment by kylewlacy** [comment]
I agree that it would definitely be better to reflect the option in the Preference Pane. I spent some time on tweaking the code to amend to my PR, and I ended up finding a kind of strange (and somewhat unrelated) issue with the "ControllerType" setting value that I couldn't figure out how to fix:

Based on [this code](https://github.com/360Controller/360Controller/blob/master/Pref360Control/Pref360ControlPref.h#L43-L44), I believe that the value of "ControllerType" for an Xbox One controller should always be either 2 (`XboxOneController`) or 3 (`XboxOnePretend360Controller`).

I noticed, with some `NSLog`s and reading `com.mice.driver.Xbox360Controller.devices.plist` that "ControllerType" always seems to be 0 (for the Xbox One controller I'm using). In the Preference Pane, this means that the "Rumble Options" [always shows "Default" and "None"](https://cloud.githubusercontent.com/assets/1362179/14766253/52dba1e6-09b7-11e6-912c-f8703571d767.png) (but should include [extra options](https://github.com/360Controller/360Controller/blob/e13d3adab9dc3d5f06d32f441b87be77d36d4f40/Pref360Control/Pref360ControlPref.m#L91-L92)). Here are some steps to reproduce:

1. Uninstall 360Controller (using the button in the Preference Pane > Advanced)
2. Reboot
3. Delete `/Library/Preferences/com.mice.driver.Xbox360Controller.devices.plist`
4. Install 360Controller (using the beta-6 `.pkg`) and reboot again
5. Connect an Xbox One controller
6. Change an option in the Preference Pane (such as toggling "pretend to be an Xbox 360 controller") in order to write the `plist` file to disk
7. Run `defaults read /Library/Preferences/com.mice.driver.Xbox360Controller.devices.plist`. Notice that the "ControllerType" field is 0

And here's my Xbox One controller device info from System Information:

```
Controller:

  Product ID:                    0x02dd
  Vendor ID:                     0x045e  (Microsoft Corporation)
  Version:                       2.03
  Serial Number:                 7EED88D08E58
  Speed:                         Up to 12 Mb/sec
  Manufacturer:                  Microsoft
  Location ID:                   0x3d200000 / 1
  Current Available (mA):        1000
  Current Required (mA):         500
  Extra Operating Current (mA):  0
```

--------

I think if the above issue is resolved, I can finish up the changes to the Preference Pane (to distinguish spoofed Xbox One controllers from 360 controllers) and add that to my PR

**Comment by kylewlacy** [comment]
Oh, and it is extremely silly to detect a gamepad by checking its product string! Personally, though, I think if 360Controller is going to have an option to make One controllers appear as 360 controllers, it should go as far as possible to appear as a 360 controller, including changing the product string. However, if you (or the other 360Controller maintainers) disagree with that notion, then I think that's totally fair, so feel free to close the PR if that's the case (and I shot an email to the developers of Brawlhalla about this issue, so hopefully that particular problem will be resolved anyway!)

**Comment by FranticRain** [comment]
So you've found the settings bug. That one has been around for longer than I have. See #67 #142 #181. That's partially why I set that string there in the driver instead of in the preference pane. The settings to eventually load in correctly, just not immediately. Honestly, I don't understand it, but its a long standing problem. No one so far has found a good solution.

I understand your point about the Xbox One controller doing its best to imitate the 360 controller. But I value the usability of the driver over compatibility with a few poorly programmed indie games.

**Comment by kylewlacy** [comment]
First off, for clarity: if I *do* fix the displayed controller name in the Pref Pane (which I haven't done because of the above settings issue, #67), is this PR still on the table for being merged in?

Second, I'm interested in trying to fix #67 (regardless), so I've beed doing some digging in the codebase. I'm a little confused about how settings are managed in 360Controller. It seems that there are 2 places where settings are stored: at the driver level (through `IORegistryEntrySetCFProperties`, etc.), and in `com.mice.driver.Xbox360Controller.devices.plist` (through `CFPreferencesSetValue`, etc.). It seems that these 2 data stores contain the same information for the most part, but can cause problems with inconsistencies. For example, try this:

1. Go to the Preference Pane and turn off "pretend to be an Xbox 360 controller"
2. Close the Preference Pane
3. Run `defaults read /Library/Preferences/com.mice.driver.Xbox360Controller.devices.plist` to find the serial number for the Xbox One controller
4. Run `defaults write /Library/Preferences/com.mice.driver.Xbox360Controller.devices.plist [serial#] -dict-add Pretend360 1`
5. Open the Preference Pane again, go to the Advanced tab

Notice that ["pretend to be an Xbox 360 controller" option is checked, while the controller name is still listed as "Xbox One Wired Controller (Wired)"](https://cloud.githubusercontent.com/assets/1362179/14771706/290452dc-0a48-11e6-9e23-68f97517a81e.png). Changing another setting (such as the stick deadzone setting), leaving the Pref Pane, and re-entering the Pref Pane fixes this, changing the device name to the expected "Xbox One Wired Controller (Xbox 360) (Wired)".

The issue here (I suspect) is that the Pref Pane writes both to the `plist` and the IORegistry, but only reads from the IORegistry when setting up the UI. When changing another preference, both get written to, which syncs the two data stores again.

So, my second question is: is there a compelling reason for there to be 2 data stores for controller settings (or am I just mis-reading how settings are handled)? I can't say for certain, but I suspect this is related to #67 somehow. Like I said, I'd be interested in contributing another PR for a fix, and this is just something I noticed while going through the code.

(Also, do the 360Controller devs have a preferred place for these kinds of discussions/questions (like IRC), or do you usually just go through GitHub issues?)

**Comment by FranticRain** [comment]
1. I would definitely accept the pull request, yes.
2. You're going to have to run that by people who have been around longer than I have. I don't know how any of that settings stuff works at all.

**Comment by electric-monk** [comment]
From what I recall of the settings stuff, the IO Registry isn't persistent, it's simply a reflection of current state. I also didn't want to mess around with file I/O from the kernel for obvious reasons, so to make the settings in the preference pane persist, and not require the preference pane to run, I also had to add the small daemon. Otherwise, you'd only get settings when you loaded the prefpane.

The daemon also sets the LEDs for 1-4, but that's mostly just a secondary function (the tertiary function being showing that alert to stop people trying to use the charging cable to use the wireless controller), primarily it configures the IO Registry with the settings from the plist files. The preference pane writes to both as when you set it, it should both save that info and make sure the connected controller's driver is up to date

**Comment by kylewlacy** [comment]
Alright @FranticRain, I changed it so that Xbox One controllers now appear as Xbox One controllers in the device list:

"Xbox One Controller (Xbox 360) (Wired)"

**Comment by FranticRain** [comment]
Okay, I'll play around with it for a bit and if everything looks good, I'll merge it and promote a new build.

**Comment by kylewlacy** [comment]
Actually, there's one more (separate) PR I want to submit (to fix 2 separate issues related to button remapping). I should have it done within about a couple hours or so, if you wanted to hold off on the new build until then.

The issues are:
1. Clicking the "reset mapping" button doesn't work if you haven't clicked the "start remapping" button yet since opening the Pref Pane
2. Clicking "start remapping" should reset the button bindings (currently, mapping A -> B, then mapping B -> X will actually cause A -> X to be mapped)

**Comment by FranticRain** [comment]
It occurred to me randomly while writing patch notes, using this hardcoded name scheme, did the game still work with wireless controllers? I guess they looked for either product string and used it if it matched.

**Comment by kylewlacy** [comment]
@FranticRain yep, it works fine with a wireless 360 controller!

**Pull request merged**
