### PR TITLE
Fix Xone Implementation, Add Controllers

### LINKED ISSUE #178: Change link in About to new repo
The About page in the preference pane still links to the old GitHub page.

### PR DESCRIPTION
**Pull request by FranticRain**
**PULL REQUESTS ARE NOT AN OPEN FORUM FOR YOUR QUESTIONS. CREATE AN ISSUE. THAT IS WHAT ISSUES ARE FOR.**

Replacement for #151. Apparently my computer decided that it wanted to unlink my github account and then created some bogus account with a random email address. Unfortunately, it means that all of my commits get flattened down to this.

Resolves #178 #175 #171 #160 #146 

As with the final post on #151:
@RodrigoCard Okay, it's all up to date. The only remaining thing is a checkbox that makes Xbox One controllers pretend to be 360 controllers. It only does anything for Xbox One controllers, and probably shouldn't show up for any other controller type. The checkbox needs to hook into the "Pretend360" setting flag, and it should work perfectly. I couldn't figure out where it should go, so I'll leave that part up to you.

### CODE REVIEW

**Comment by FranticRain** [comment]
Added #173 #159 #145 to Info.plist

**Comment by RodrigoCard** [comment]
Right! I will do this today.

Em sexta-feira, 25 de dezembro de 2015, Drew Mills <notifications@github.com>
escreveu:

> Added #173 <https://github.com/360Controller/360Controller/issues/173>
> #159 <https://github.com/360Controller/360Controller/issues/159> #145
> <https://github.com/360Controller/360Controller/issues/145> to Info.plist
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/360Controller/360Controller/pull/184#issuecomment-167191704>
> .
>


-- 
Enviado do Gmail para celular

**Comment by andreasnilsson** [comment]
As I understand it, this will add support for the elite controller? 
If so, is there a binary compiled for us who want to try it out?

**Comment by FranticRain** [comment]
@andreasnilsson Try this out. Its not fully featured, but it should get output from the Xbox One Elite controller just fine. https://drive.google.com/file/d/0B5PLCKoMd4zGajhnQWxJUXA2UVk/view?usp=sharing

**Comment by andreasnilsson** [comment]
@FranticRain Thanks! Just installed it and now it's recognized :+1: 
It's seems pretty erratic in terms of which keys are lighted up when I use it though.

Is there anything I can do to help you out?

**Comment by FranticRain** [comment]
@andreasnilsson Check and uncheck swap sticks, then try to rebind the buttons using the rebind functionality. Press the same button as the one that lights up, and tell me what numbers you get.

**Comment by RodrigoCard** [comment]
Baaaad news.... I forgot my Macbook in another city!
I will only be able to get it back in a week.... I am feeling so dumb!! -.-


Em domingo, 27 de dezembro de 2015, Drew Mills <notifications@github.com>
escreveu:

> @andreasnilsson <https://github.com/andreasnilsson> Check and uncheck
> swap sticks, then try to rebind the buttons using the rebind functionality.
> Press the same button as the one that lights up, and tell me what numbers
> you get.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/360Controller/360Controller/pull/184#issuecomment-167414277>
> .
>


-- 
Enviado do Gmail para celular

**Comment by FranticRain** [comment]
@RodrigoCard No worries. It looks like when I compressed this down the Elite support got messed up somehow. Wish I could figure out whats going on.

**Comment by FranticRain** [comment]
@andreasnilsson Okay, I made a build with less features that could be causing problems and more debugging features. You can't invert sticks or rebind controls in this build. Its pretty much just raw input from the controller, with some necessary tweaking of the triggers. So here's how you can test this for me. Open up Console.app located in your Application/Utilities folder. On the left hand panel, click on system.log. Now, when you plug in your controller, you will get a bunch of stuff. I only care about stuff that is prefixed with `Elite - `. Now, if it just starts spitting out a bunch of junk with `BUTTON PACKET` in it, unplug it pretty much immediately. If it doesn't, press some buttons on the controller and then unplug it. Then I'll need to see the output of that log, and I'll need you to tell me how it acted. I should be able to fix it from there. https://drive.google.com/file/d/0B5PLCKoMd4zGbGtFRDBWU0ZxNkE/view?usp=sharing

**Comment by JennaShelley** [comment]
Have you made any drivers that work for the newer xbox one controllers??? i can't seem to find any!!

**Comment by FranticRain** [comment]
@JennaShelley The current release should work with any and all Xbox One controllers, barring the Elite controller. if your controller is not recognized, please create a new issue with the product and vendor IDs of your controller found in the "About This Mac -> System Report -> USB" section of your computer.

**Comment by JennaShelley** [comment]
Can you send me the link to the current release so I may try it

On Sunday, December 27, 2015, Drew Mills <notifications@github.com> wrote:

> @JennaShelley <https://github.com/JennaShelley> The current release
> should work with any and all Xbox One controllers, barring the Elite
> controller. if your controller is not recognized, please create a new issue
> with the product and vendor IDs of your controller found in the "About This
> Mac -> System Report -> USB" section of your computer.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/360Controller/360Controller/pull/184#issuecomment-167484515>
> .
>


-- 
- Jenna

**Comment by FranticRain** [comment]
@JennaShelley Releases, as always, are in the releases section of this repository. https://github.com/360Controller/360Controller/releases

**Comment by andreasnilsson** [comment]
@FranticRain 
I just tried out the latest driver one you posted to me, and with that one everything seems to work fine with it. The only caveat is that the analog sticks are vertically inverted.

I can navigate around with it in steam using big picture mode and steam recognizes it.

Looking at the console; all I get with the `Elite` tag is Button packets, except when I first plug it in. Then I get this packet as well: `2015-12-28 11:04:22,000 kernel[0]: Elite - Made Elite Peripheral 1`

**Comment by iceman64128** [comment]
Does this recently posted build also include the support for the wireless adapter?

**Comment by FranticRain** [comment]
@iceman64128 No, no progress has been made on that yet.

@andreasnilsson That's great news. That narrows things down a lot. I'll try and figure it out and get back to you ASAP.

**Comment by FranticRain** [comment]
@andreasnilsson Okay, I did a build that removed the debug stuff, and should work perfectly, except you can't rebind the controller. I sometimes think that feature is more trouble than it is worth. Let me know if this works properly. https://drive.google.com/file/d/0B5PLCKoMd4zGZ1paangxLTZLaVk/view?usp=sharing

**Comment by andreasnilsson** [comment]
@FranticRain It works great! The sticks are moving as expected now. 

I agree since you normally can rebind the controller within the game.

One feature I'd like to see is the ability to set the deadzone for the analog sticks. It can also be noticed inside the app that they stop off center, which of course has to do with them being analog, but sometimes this is not wanted behavior.

**Comment by FranticRain** [comment]
@andreasnilsson You should be able to set deadzones within the "Xbox 360 Controllers" preference pane in your System Preferences. If you go to the advanced tab, you can get some more detailed information.

**Comment by FranticRain** [comment]
@andreasnilsson Okay, if you want to help me fix the rebinding, I'm going to need you to install this release and tell me what `Elite - BUTTON PACKET - ` says. It will be different than the currently installed version. I only care what the new values are though, not the old ones. https://drive.google.com/file/d/0B5PLCKoMd4zGeUY4ZEh6cUhQbms/view?usp=sharing

**Comment by FranticRain** [comment]
@RodrigoCard I went ahead and removed the Elite remapping from the pull request, so this thing is good to go for now. If I can figure out the Elite mapping afterwards, I'll patch it in and put out an official release after this current one coming up. I need to stop letting this all pile up and ending up with these million feature pull requests.

**Comment by TyanColte** [comment]
@FranticRain Ok, this got super confusing super fast. What happened? I saw Rodrigo's post on #151 to check the release on #184 but I'm not sure if what that's supposed to do. Is there an official release coming soon? Does that unofficial release you posted a while ago have a signed kext? If so do you need me to test it?

**Comment by FranticRain** [comment]
@TyanColte I made some git mistakes that made #151 unusable, but this one is perfectly fine. All of the drive links on this page are fully signed. The most recent one is signed, and should work perfectly with an Xbox One Elite controller. It doesn't have any rebinding features though. Something is wrong with it, so I'm trying to work it out. If you could download the last drive link and tell me what you get in your system.log, that would be great.

**Comment by Vilmoss28** [comment]
Hi
I recently bought the lunar edition Xbox one special edition controller and was wondering since it is a newly released controller if it is compatible with the drivers

**Comment by FranticRain** [comment]
@Vilmoss28 Pull requests are not an open forum for questions. Create an issue. That is what issues are for. By commenting in a pull request, you are only hindering us from putting out a new release. As for your question, why didn't you just try installing the driver? That would probably be the easiest course of action. Undoubtedly it is, its just a paint job. If it isn't, post the vendor and product IDs in a new issue, just like all new devices.

**Comment by TyanColte** [comment]
@FranticRain Ok, as soon as I have a free afternoon I will do just that. It's been a very busy week, catching up from the Christmas vacation.

**Comment by RodrigoCard** [comment]
So, I got my macbook back, re-installed xcode 6.4 again and built it.

If someone is interested in testing, please do ! :)
https://dl.dropboxusercontent.com/u/14890209/360ControllerInstall_beta4_preview.dmg

I think it is reasonable to release another beta after this pull if everything is al right.

**Comment by TyanColte** [comment]
@RodrigoCard can't test, kext not signed according to kextutil

**Comment by TyanColte** [comment]
@FranticRain testing your most recent one now.

**Comment by TyanColte** [comment]
@FranticRain 2013 controller: works
2015 controller (Recently acquired): works but buttons were screwed up until i swapped sticks and back (settings bug strikes again)
elite controller: gets recognized but neither buttons nor axises work at all in the pref pane (will test in a game and get back to you)

**Comment by TyanColte** [comment]
@FranticRain update, when i closed the prefpane for the 360 controller it crashed. I'll post the crash log in a pastebin and link it here momentarily.

**Comment by TyanColte** [comment]
https://pastee.org/z8ex8

**Comment by FranticRain** [comment]
@TyanColte  didn't really even touch the preference pane, so I probably didn't have anything to do with that. Did you get any output into your log with the elite controller?

**Comment by TyanColte** [comment]
@FranticRain didn't check, will do so now

**Comment by TyanColte** [comment]
12/30/15 9:13:03.000 PM kernel[0]: Unknown device release 203
12/30/15 9:13:03.000 PM kernel[0]: start - unable to find chatpad interface
12/30/15 9:13:03.000 PM kernel[0]: IOHIDDevice::newUserClient called on an inactive device
12/30/15 9:13:03.000 PM kernel[0]: IOHIDDevice::newUserClient called on an inactive device
12/30/15 9:13:03.000 PM kernel[0]: IOHIDDevice::newUserClient called on an inactive device
12/30/15 9:13:04.000 PM kernel[0]: IOHIDDevice::newUserClient called on an inactive device

@FranticRain this is the only things that came up when i plugged in my elite controller.

**Comment by FranticRain** [comment]
@TyanColte And you're 100% certain you installed, because @andreasnilsson claims that it works with his Elite controller. I can't imagine it working with one Elite controller and not another. https://drive.google.com/file/d/0B5PLCKoMd4zGeUY4ZEh6cUhQbms/view?usp=sharing

**Comment by TyanColte** [comment]
I'm 100% sure. i uninstalled the old version and installed that one you have there.

**Comment by FranticRain** [comment]
@TyanColte And pressing buttons puts nothing in the system log?

**Comment by TyanColte** [comment]
Nope

**Comment by FranticRain** [comment]
@TyanColte Okay, try https://drive.google.com/file/d/0B5PLCKoMd4zGZ1paangxLTZLaVk/view?usp=sharing It shouldn't put anything special in your log, but it is definitely confirmed to work with Elite controllers.

**Comment by TyanColte** [comment]
Recognized the controller. didn't move anything in the pref pane as before. and tried it in a game and the controls were all screwed up.

**Comment by FranticRain** [comment]
@TyanColte Make sure to test every controller binding issue with a normal Xbox One controller as well now, since this is the build that makes Xbox One controllers stop acting like Elite controllers. That may have nothing to do with the Elite controller specifically.

**Comment by TyanColte** [comment]
ok, what the crap. i plugged in and tested the 2013 controller with the same game and it worked in that the controller worked but the buttons were mismapped. ironically when i just plugged my elite back in it went all crazygonutz in the prefpane. then i unplugged and replugged it and it started working JUST FINE! going to go back and test it with that game again.

**Comment by TyanColte** [comment]
Ok, not only is my elite controller working now perfectly the game picked it up as a 360 controller and is mapped perfectly! i have no idea what changed. but all is right with the world for the time being.

**Comment by FranticRain** [comment]
@TyanColte Okay now if you install https://drive.google.com/file/d/0B5PLCKoMd4zGZ1paangxLTZLaVk/view?usp=sharing what happens?

**Comment by TyanColte** [comment]
should i uninstall the other one first?

**Comment by FranticRain** [comment]
@TyanColte Doesn't matter. It will install over itself just fine.

**Comment by TyanColte** [comment]
Figured as much. That's what i've been doing, will test and try again

**Comment by TyanColte** [comment]
Works perfectly again. On FEZ it works great and it's seen as a 360 controller. But on something like BattleBlock Theater. it doesn't even work. Nor does the 2013 or 2015 controllers. So that game must be looking for something specific.

**Comment by TyanColte** [comment]
Works great on games like FEZ and Hack 'n Slash, but things like Broforce (Which is very crashy anyway), battle block theater and shank it's a no go.

**Comment by FranticRain** [comment]
@TyanColte I want to make absolutely certain, in the pref pane, what is the controller labeled as? Is it: "Xbox One Wired Controller", "Xbox One Wired Controller (Xbox 360)", or "Xbox One Elite Wired Controller"? I'd like to know for either 2013 or 2015, as well as the Elite controller.

**Comment by TyanColte** [comment]
The Elite controller is labeled as such "Xbox one Elite Wired Controller" 
The 2013 controller is labeled as "Xbox One Wired Controller (Wired)"
The 2015 controller is labeled as "Xbox One Wired Controller (Wired)"

**Comment by FranticRain** [comment]
@TyanColte Okay I think I got a handle on this. Do you get any output to the system.log from the Elite controller when you press buttons?

**Comment by TyanColte** [comment]
@FranticRain I'm off to bed for tonight. I'll check tomorrow if it's all the same.

**Comment by FranticRain** [comment]
@TyanColte I still need to know what the output is in the system log from the Elite controller. It should have a message that starts with `BUTTON PACKET - ` that lists out the mappings. I need it to fix the remapping functionality, otherwise is just going to remain off.

**Comment by TyanColte** [comment]
@FranticRain I'll get to that today. It's been a busy week. I finally have some time today to goof around with other things. So I'll get that to you ASAP.

**Comment by TyanColte** [comment]
@FranticRain I'm not getting anything in the log except for diagnostic messages from plugging it in. No output when pressing buttons. Is it possible i don't have the proper version for that to happen?

**Comment by RodrigoCard** [comment]
@TyanColte sorry about that, every merge messes with sign stuff...

@FranticRain I did lots of tests now. here are my findings:

- The rumble testing is now working in the prefpane :)
- Towerfall DOES NOT WORK anymore with my xbox one (2013) controller! (but does with wireless 360)
- I tested and it worked perfectly when it was pretending to be a 360 controller... So, it must be expecting a 360 controller, probably. Which makes me think that pretending to be a 360 controller should be the default option...

- I found a bug in the default mappings of xbox one controller if you have another controller connected together, look:
2_xbox_controllers
- In this case I pressed ABXY buttons and DPAD down. As you can see, different button indexes are highlighted. And dpad down does not register at all in xbox one controller.
- This does not happen the first time I connect the xbox one controller after booting... except for the Dpad which is wrongly mapped anyway.
- The xbox one controller includes a extra useless button (mapped to 11)
- Starting and reseting remapping reverts to the fresh boot mappings (which is still wrong because of the extra button)
- also:
screencaps
Here, I am pressing the X button in the xbox one controller, with the default mapping.

**Comment by FranticRain** [comment]
@RodrigoCard Now you see where I was coming from with the pretend 360 stuff!
- We can make pretend360 default to true, and then the onus will be on devs to tell people to deactivate the pretend mode if their game supports extra Xbox One features.
- Activate and deactivate a setting like Swap Sticks to fix the mapping on the second controller. It's sort of related to the settings bug. If you see, there is a new function in `_60Controller.cpp` called `MakeSettingsChanges().` It's a bit bulky, I need to clean it up, but it forcibly remaps 360 bindings to Xbox One bindings if needed. Whats happening is that the controller is not loading its settings properly when connected second. Therefore it gets the default Xbox 360 mapping, which is exactly what you see. As soon as you activate some setting, it calls `setProperties()` which calls `MakeSettingsChanges()` and it's all solved. I'm not sure how to fix this one. Maybe moving that function into the Pref Pane might help? I'm not sure.
- Button 12 (1 index) or 11 (0 index) is the sync button. That's some vestigial stuff from my code, we can remove it if you want.

Now I used my own build I've been working with locally so I don't know all the specifics of what you added. So here is some stuff that might be related to that.
- I only get rumble on the second controller, not on the first.
- My D-Pads aren't wrongly mapped, so I'm not sure what you're talking about.
- Resetting the remapping works fine for me,

**Comment by RodrigoCard** [comment]
It is currently the most usable form for most games.
But I agree that pretending to be a xbox 360 controller shouldn't be the default.
However, I think it should *for now*, while the settings couldn't be saved properly.
So we can release a new beta with Elite and more devices supported before :)
What you think?

About The sync button: I think it shouldnt be accessible, as it would create inconsistent behavior once we support wireless xbox one controllers.

*But It is useful to have an extra button...*

The problem of the dpad is that they are mapped to 12/13/14/15 buttons in xbox one controllers and 11/12/13/14 buttons in xbox 360 controllers. I just tested that (the other buttons mappings are ok).

The extra button itself is not a problem, the problem is that it does not match the xbox 360 order.

So, if the button is removed OR it is moved to the end of the list, problem solved! :)

Feel free to disagree :)

**Comment by FranticRain** [comment]
Sounds good to me. I went ahead and changed `xboxOnehid.h` so that the sync button is commented out, and the D-Pad is moved into the correct position. I moved the sync button to the last button, just in case we want to uncomment it later on. I'll let you set the default for Pretend360 since you have UI changes I don't have. One more thing though, I always mess up the .xcodeproj when I mess with it, so can you add `xboxOnehid.h` to the project for me?

Other than that, it looks like we are good to go.

**Comment by RodrigoCard** [comment]
Ok. I will test again, add the file and merge if everything is okay (ignoring the settings bug of course).
And add the UI option after that.

Also, I agreed with @d235j to include you as a member of the project.
But haven't heard of him since then... @d235j are you there? :)

**Comment by FranticRain** [comment]
He did add me, I have the little collaborator flag. I just like to have others check my work before I go around accepting pull requests and such.

**Comment by d235j** [comment]
@FranticRain I sent you an email indicating you got added; not sure whether it got lost...

**Comment by FranticRain** [comment]
@d235j Yup, I did get it. Thank you very much.

**Comment by RodrigoCard** [comment]
I agree with you @FranticRain , I like other to check my work too :)
I just didnt find you in the organization's collaborator list:
https://github.com/orgs/360Controller/people

Do you have access to make releases?
I would be good, since you got the certificate....
just in case I vanish from the internet for some time again :)

**Comment by TyanColte** [comment]
@FranticRain @RodrigoCard Let me know if I need to do more testing with the elite controller. I'm no coder but I feel that my testing has improved the elite controller's compatibility by leaps and bounds. Just let me know what you need me to do.

**Comment by FranticRain** [comment]
@RodrigoCard Yup, I definitely can make releases.
@TyanColte I just need those numbers from the log from you for now.

**Comment by TyanColte** [comment]
@FranticRain Like i said before, nothing comes up in the console when i push buttons. I don't know if i have the correct version for it to do that.

**Comment by FranticRain** [comment]
@TyanColte Okay, try this one and let me know if it completely ruins your mapping on the Elite controller. It shouldn't change anything about your other controllers. https://drive.google.com/file/d/0B5PLCKoMd4zGZ0ZKb2k4M3dseEU/view?usp=sharing

**Comment by TyanColte** [comment]
@FranticRain Elite - BUTTON PACKET - 8, 9, 10, 11, 2, 3, 14, 15, 12, 13, 0, 4, 5, 6, 7

**Comment by FranticRain** [comment]
@TyanColte Thanks. It looks like its just a settings bug, and for some reason it works for some and not for others. If we default Pretend360 to on, we should be solid though. That's good news.

**Comment by TyanColte** [comment]
@FranticRain How's everything looking? Haven't heard anything in a while.

**Comment by FranticRain** [comment]
@TyanColte Your guess is as good as mine. I could do a proper release, but I honestly don't know where to put the "Pretend 360" checkbox. Extended stretches of silence from the rest of the development team is pretty normal around here.

**Comment by TyanColte** [comment]
@FranticRain Ah, well I appreciate you replying so quickly. If you ask me I'd just put it wherever or make a new tab for it or something. Just so you can get a release out.

**Comment by RodrigoCard** [comment]
I was thinking about a new tab too. Moving the "rumble options" to it too.
Changing the "advanced" tab to something else too, since it is a
bit convoluted.
What you think?


-- 
Enviado do Gmail para celular

**Comment by FranticRain** [comment]
Rumble options are useful for controllers other than the Xbox One controller, so we can't just call it an Xbox One controller tab. I don't know exactly what we'd call a new "Advanced" tab. It has some "advanced" readings from the joysticks, and it houses the controller enable, disable, and uninstall. It isn't exactly something that is easy to group with a word or phrase other than "Advanced."

**Comment by TyanColte** [comment]
@FranticRain @RodrigoCard You could make a new tab called "Driver options" and move the driver stuff in there. and put the Pretend 360 option and rumble options in the "Advanced" tab. This is just me taking a shot in the dark.

**Comment by FranticRain** [comment]
I just added the toggle to the advanced tab, so when someone better with the pref pane than me decides to reorganize it, it will make sense that it moved.

Also the `xboxonehid.h` file still isn't in the xcodeproj because I always mess the xcodeproj up somehow.

But I'm just going to do a release anyway.

**Comment by RodrigoCard** [comment]
Nice! I am a bit busy but I will reorganize later the preference pane if necessary.
Feel free to release as is, anyway :)

**Comment by Vilmoss28** [comment]
Can you add support for the Logitech g920 product id: 0xc261
Vendor Id: 0x046d

**Comment by FranticRain** [comment]
@Vilmoss28 Here you go: https://drive.google.com/file/d/0B5PLCKoMd4zGMVpHYVpQYWlPQnc/view?usp=sharing

**Comment by Vilmoss28** [comment]
K thx

**Comment by Vilmoss28** [comment]
Not on iMac at the mo will be able to download it in the morning

**Pull request merged**
